conditions:
  BABEL_8_BREAKING:
    default: false
  USE_ESM:
    default: false

enableGlobalCache: true

enableTransparentWorkspaces: false

# Disable postinstall scripts.
enableScripts: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-babel-release-tool.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-babel-release-tool/main/bundles/%40yarnpkg/plugin-babel-release-tool.js"
  - path: .yarn/plugins/@yarnpkg/plugin-conditions.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-conditions/main/bundles/%40yarnpkg/plugin-conditions.js"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

releaseTool:
  ignoreChanges:
    - "*.md"
    - "*.txt"
    - test/**
    - "**/test/**"
    - codemods/**
    - "@(!(native-modules|built-ins|plugins|package|corejs2-built-ins|corejs3-shipped-proposals|plugins-bugfixes)).json"
  implicitDependencies:
    "@babel/runtime":
      - "@babel/helpers"
    "@babel/runtime-corejs2":
      - "@babel/helpers"
    "@babel/runtime-corejs3":
      - "@babel/helpers"

unsafeHttpWhitelist:
  - localhost

packageExtensions:
  jest-snapshot@*:
    dependencies:
      # It doesn't support Prettier 3 yet
      prettier: "^2.0.0"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
