name: E2E tests (breaking)

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-publish:
    name: Publish to local Verdaccio registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Publish
        run: ./scripts/integration-tests/publish-local.sh
        env:
          BABEL_8_BREAKING: true
      - uses: actions/upload-artifact@v3
        with:
          name: verdaccio-workspace
          path: /tmp/verdaccio-workspace

  e2e-tests:
    name: Test
    needs: e2e-publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - babel
          - create-react-app
          - vue-cli
          - jest
          # todo: Enable this test when metro-source-map does not reassign NodePath cache
          # https://github.com/facebook/metro/blob/29bb5f2ad3319ba8f4764c3993aa85c15f59af23/packages/metro-source-map/src/generateFunctionMap.js#L182
          # react-native
          - prettier
          - angular-cli
    steps:
      - name: Get yarn1 cache directory path
        id: yarn1-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
      - name: Get yarn3 cache directory path
        id: yarn3-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use yarn1 cache
        uses: actions/cache@v3
        id: yarn1-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn1-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn1-e2e-breaking-${{ matrix.project }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn1-e2e-breaking-${{ matrix.project }}-
      - name: Use yarn3 cache
        uses: actions/cache@v3
        id: yarn3-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn3-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn3-e2e-breaking-${{ matrix.project }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn3-e2e-breaking-${{ matrix.project }}-
      - name: Clean babel cache
        run: |
          rm -rf ${{ steps.yarn1-cache-dir-path.outputs.dir }}/*babel*
          rm -rf ${{ steps.yarn3-cache-dir-path.outputs.dir }}/*babel*
      - uses: actions/download-artifact@v3
        with:
          name: verdaccio-workspace
          path: /tmp/verdaccio-workspace
      - name: Test
        run: ./scripts/integration-tests/e2e-${{ matrix.project }}.sh
        env:
          BABEL_8_BREAKING: true
